spring.application.name=froid-cheikh-ecommerce
server.port=

# Datasource - utilise les variables Railway
spring.datasource.url=jdbc:postgresql://dpg-d7dvgid8nd3s73b7muqg-a:5432/froid_cheikh_db
spring.datasource.username=froid_cheikh_db_user
spring.datasource.password=a7cwjnYT0V9gT6gjCi5A47yaP1gz8Jwn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=mySecretKey1234567890123456789012345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=app/uploads

file.upload-dir=/tmp/uploads